services:
    # custom fosuser user manager    
    pugx_user.manager.orm_user_manager:
        class:     PUGX\MultiUserBundle\Doctrine\UserManager
<<<<<<< HEAD
        arguments: ["@security.encoder_factory", "@fos_user.util.username_canonicalizer", "@fos_user.util.email_canonicalizer", "@fos_user.object_manager", "%fos_user.model.user.class%", "@pugx_user.manager.user_discriminator"]
=======
        arguments: ["@fos_user.util.password_updater", "@fos_user.util.canonical_fields_updater", "@fos_user.object_manager", "%fos_user.model.user.class%", "@pugx_user.manager.user_discriminator"]
>>>>>>> refs/remotes/origin/master
        
    pugx_user_manager:
        alias: pugx_user.manager.orm_user_manager
